// Navbar show on scroll
var prevScrollpos = window.pageYOffset;
window.onscroll = function () {
  var currentScrollPos = window.pageYOffset;
  if (window.pageYOffset === 0) {
    $("#navbar").css("top", "0");
  } else if (prevScrollpos > currentScrollPos) {
    $("#navbar").css("top", "0");
  } else {
    $("#navbar").css("top", "-50px");
  }
  prevScrollpos = currentScrollPos;
};

let year = new Date().getFullYear();
$("#currentYear").html(year);

// Enable Popovers
$(function () {
  $('[data-toggle="popover"]').popover();
});

$(".popover-dismiss").popover({
  trigger: "focus",
});

// Form handling
const name = document.getElementById("name");
const email = document.getElementById("email");
const message = document.getElementById("message");

//Show input error message
function showError(input, message) {
  const validation = input.parentElement;
  $(validation).addClass("error");
  const small = validation.querySelector("small");
  $(small).text(message);
}

// Show success outline
function showSuccess(input) {
  const validation = input.parentElement;
  validation.className = "success";
}

// Check email is valid
function checkEmail(input) {
  const regex = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
  if (regex.test(input.value.trim())) {
    showSuccess(input);
  } else {
    showError(input, "Email is not valid");
  }
}

//Check required fields
function checkRequired(inputArr) {
  inputArr.forEach((input) => {
    if (input.value.trim() === "") {
      showError(input, `${getFieldName(input)} is required`);
    } else {
      showSuccess(input);
    }
  });
}

// Check input Length
function checkLength(input, min) {
  if (input.value.length < min) {
    showError(
      input,
      `${getFieldName(input)} must be at least ${min} characters`
    );
  }
}

// Get fieldname
function getFieldName(input) {
  return input.id.charAt(0).toUpperCase() + input.id.slice(1);
}

$("#form").submit(function (e) {
  e.preventDefault();
  checkRequired([name, email, message]);
  checkLength(message, 3);
  checkEmail(email);
});

// Toast
let messageList = [
  {
    message:
      "Did you know? Over 3 million dollars were transactioned by businesses using our technology just this month!",
    time: "7 mins ago",
  },
  {
    message:
      "Did you know? We just hit 1.000.000 users! Thank you for your support!",
    time: "3 mins ago",
  },
  {
    message:
      "Did you know? This little message was generated by a customized jQuery and not just the Bootstrap standard procedures, but I promise this is the last one ;)",
    time: "Just now",
  },
];
let i = 0;
let delay = 2000;

$(document).ready(function toast() {
  setTimeout(() => {
    $("#toastTime").html(messageList[i].time);
    $("#toastMessage").html(messageList[i].message);
    $(".toast").toast("show");
    i++;
    delay = 8000;
    if (i >= messageList.length) {
      return;
    } else {
      toast();
    }
  }, delay);
});

// Floating iPhone
let eventCount = 0;

$("#touchArea").on("touchstart", () => handleFloating());
$("#touchArea").on("mouseenter", () => handleFloating());
$("#touchArea").on("mouseleave", () => handleFloating());

function float() {
  $("#iphoneFloating").removeClass("change-position");
  $("#shadowFloating").removeClass("change-position-shadow");
  $("#iphoneFloating").addClass("change-back");
  $("#shadowFloating").addClass("change-back-shadow");
  $("#iphoneDisplay").removeClass("show-display");
  setTimeout(() => {
    $("#iphoneFloating").removeClass("change-back");
    $("#shadowFloating").removeClass("change-back-shadow");
    $("#iphoneFloating").addClass("floating");
    $("#shadowFloating").addClass("floating-shadow");
  }, 3000);
}

function unfloat() {
  $("#iphoneFloating").removeClass("change-back");
  $("#shadowFloating").removeClass("change-back-shadow");
  $("#iphoneFloating").addClass("change-position");
  $("#shadowFloating").addClass("change-position-shadow");
  $("#iphoneFloating").removeClass("floating");
  $("#shadowFloating").removeClass("floating-shadow");
  $("#iphoneDisplay").addClass("show-display");
}

function handleFloating() {
  if (eventCount == 0) {
    unfloat();
    $("#iphoneDisplay").css("display", "block");
    $("#iphoneDisplay").addClass("show-display");
    eventCount++;
  } else if (eventCount == 1) {
    $("#iphoneDisplay").css("display", "none");
    $("#iphoneDisplay").css("opacity", "0");
    $("#iphoneDisplay").removeClass("show-display");
    float();
    eventCount++;
  } else if (eventCount == 2) {
    unfloat();
    $("#iphoneDisplay").css("display", "block");
    setTimeout(() => {
      $("#iphoneDisplay").css("opacity", "1");
    }, 3000);
    eventCount = 3;
  } else {
    $("#iphoneDisplay").css("opacity", "0");
    $("#iphoneDisplay").css("display", "none");
    float();
    eventCount = 2;
  }
}

$(document).on("DOMContentLoaded", float());

// AOS library
AOS.init({
  easing: "ease-in-quad",
});
